### ISSUE TITLE
Add commit hash/id to changelog and jar

### ISSUE THREAD

**Issue by DarkGuardsman** [BuiltBrokenModding/BuiltBrokenScripts#2]
When creating the artifacts we need to log which commit the build was created with. This way we do not have to track build numbers. Instead we can just look at the jar, pom, or change log to see what the commit number was. Then from there track back to see if issues are resolved in later commits or still exist.

**Comment by dmodoomsirius** [comment]
Still need to add to jar. going to work on that at some point.

**Comment by dmodoomsirius** [comment]
Reopened since im going to rewrite scripts to do it in every jar at once.
