### ISSUE TITLE
Add date created to change log

### ISSUE THREAD

**Issue by DarkGuardsman** [BuiltBrokenModding/BuiltBrokenScripts#3]
When creating builds we need to log when the build was created. This way users can see how old a build is on the site when downloading. As well we devs can see if its within support range to even bother fixing bugs for.

**Comment by dmodoomsirius** [comment]
Will use http://www.gradle.org/docs/current/userguide/publishing_maven.html 66.2.4. Modifying the generated POM 

http://www.gradle.org/docs/current/dsl/org.gradle.api.publish.maven.MavenPom.html#org.gradle.api.publish.maven.MavenPom:withXml(org.gradle.api.Action)

**Comment by dmodoomsirius** [comment]
Will also be worked in with https://github.com/BuiltBrokenModding/BuiltBrokenScripts/issues/1

**Comment by dmodoomsirius** [comment]
Currently in the pom file.

**Comment by dmodoomsirius** [comment]
Changelog is done
