### ISSUE TITLE
Create branches for 1.6.4, 1.7.0 and 1.8

### ISSUE THREAD

**Issue by dmodoomsirius** [BuiltBrokenModding/BuiltBrokenScripts#7]
- [x] Create 1.7.10 branch and explain what each script does
- [x] Create 1.8 branch and explain what each script does
- [x] create 1.6.4 branch and explain what each script does.

**Comment by Parker8283** [comment]
PLEASE don't go back to 1.6.4 at this point...

**Comment by dmodoomsirius** [comment]
I will have it if @DarkGuardsman needs it.

**Comment by Parker8283** [comment]
I sincerely hope he has no plans to go back to 1.6.4

**Comment by DarkGuardsman** [comment]
No parker i do work for clients often that need mods done for several MC versions. In which i have a current client that was requesting additions to a 1.6.4 mod. My current mods will remain 1.7.10 for the time being but we need scripts for several MC versions.

**Comment by Parker8283** [comment]
Well then I guess I'm more upset with people who are requesting mods for 1.6.4 and lower than you then.

**Comment by DarkGuardsman** [comment]
I wouldn't get upset most of these people are using old version because mods sometimes don't update. As well 1.6.4 has a lot of mods that are very stable and bug free. 1.7.10 is still know for having the most bugs of any MC generation.
